# Generated by Django 4.2 on 2023-04-13 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="user",
        ),
    ]
