# Generated by Django 4.2 on 2023-04-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_movie_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
